CREATE TABLE "public"."customerMaster" (
    "customerID" text,
    "FirstName" text,
    "LastName" text,
    "Email" text,
    "Salutation" text,
    "OtherStreet" text,
    "OtherCity" text,
    "OtherState" text,
    "OtherPostalCode" text,
    "OtherCountry" text,
    "MailingStreet" text,
    "MailingCity" text,
    "MailingState" text,
    "MailingPostalCode" text,
    "MailingCountry" text,
    "Phone" text,
    "Fax" text,
    "MobilePhone" text,
    "HomePhone" text,
    "OtherPhone" text,
    "Title" text,
    "Department" text,
    "AssistantName" text,
    "LeadSource" text,
    "Birthdate" date,
    PRIMARY KEY ("customerID")
);


